// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type DeleteRequest struct {
	Key string `form:"key"`
}

type DeleteResponse struct {
	Success bool `json:"success"`
}

type GetRequest struct {
	Key string `form:"key"`
}

type GetResponse struct {
	Value          string `json:"value"`
	CreateRevision int64  `json:"createRevision"`
	ModRevision    int64  `json:"modRevision"`
	Version        int64  `json:"version"`
	Lease          int64  `json:"lease"`
}

type ListRequest struct {
	Prefix string `form:"prefix"`
}

type ListResponse struct {
	Keys []string `json:"keys"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type PutRequest struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PutResponse struct {
	Success bool `json:"success"`
}
