services:
  etcd-editor:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: etcd-editor:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./etc/etcd_web_tool.yaml:/app/etc/etcd_web_tool.yaml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8888:8888"
    networks:
      - etcd-editor-network

#  nginx:
#    container_name: nginx
#    image: nginx:latest
#    logging:
#      options:
#        max-size: "128m"
#    environment:
#      - TZ=Asia/Shanghai
#    networks:
#      - etcd-editor-network
#    ports:
#      - "8000:8000"
#    volumes:
#      - /etc/localtime:/etc/localtime
#      - ./etc/nginx:/etc/nginx
#      # 前端页面构建产物，根据你实际位置进行调整编译产物目录
#      - ../frontend/dist:/var/etcd-web-tool

networks:
  etcd-editor-network:
    driver: bridge