// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type UserClassAddReq struct {
}

type UserClassAddResp struct {
}

type UserClassDeleteReq struct {
}

type UserClassDeleteResp struct {
}

type UserClassReq struct {
}

type UserClassResp struct {
}

type UserClassUpdateReq struct {
}

type UserClassUpdateResp struct {
}

type UserInfoReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type UserInfoResp struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Payload  string `json:"payload"`
}

type UserInfoUpdateReq struct {
}

type UserInfoUpdateResp struct {
}

type UserLoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Token string `json:"token"`
}

type UserRoleAddReq struct {
}

type UserRoleAddResp struct {
}

type UserRoleDeleteReq struct {
}

type UserRoleDeleteResp struct {
}

type UserRoleReq struct {
}

type UserRoleResp struct {
}

type UserRoleUpdateReq struct {
}

type UserRoleUpdateResp struct {
}
