// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"greet/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/greet/v1/from/:name/:age",
				Handler: GreetHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/greet/v2/from/:name/:age",
				Handler: GreetHandlerV2Handler(serverCtx),
			},
		},
	)
}
